// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRL51sLf7mQpwj7s6hWTnWM3AMhQ5t7rw',
    appId: '1:173795306144:web:2d683db0e7309fc26577c5',
    messagingSenderId: '173795306144',
    projectId: 'chordify-703e5',
    authDomain: 'chordify-703e5.firebaseapp.com',
    storageBucket: 'chordify-703e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE1SkCMbBsDzPqXrPz_YC1TUetSQVvXNI',
    appId: '1:173795306144:android:36b0d8cf861ef9cc6577c5',
    messagingSenderId: '173795306144',
    projectId: 'chordify-703e5',
    storageBucket: 'chordify-703e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOT6hedK-BvpxWrLt-7ETrkZuv_odKAlc',
    appId: '1:173795306144:ios:aa6876e02692ef5a6577c5',
    messagingSenderId: '173795306144',
    projectId: 'chordify-703e5',
    storageBucket: 'chordify-703e5.appspot.com',
    iosBundleId: 'com.chordify.chordifyAssignment',
  );
}
